@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniqueRecruitList
AddressBook *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniqueRecruitList
UniqueTagList -[hidden]down- UniqueRecruitList

UniqueTagList -right-> "*" Tag
UniqueRecruitList -right-> Recruit

Recruit -up-> "*" Tag

Recruit *--> "1...*" Name
Recruit *--> "*" Phone
Recruit *--> "*" Email
Recruit *--> "*" Address
Recruit *--> "*" Description
@enduml
